### ISSUE TITLE
Enable usage with other browsers

### ISSUE THREAD

**Issue by kaptoxic** [pirate/pocket-archive-stream#14]
Is it possible to make this work with other browsers, namely Firefox? (For those who don't have a possibility of using chrome.) Hopefully, the software can easily be made agnostic to the specific browser choice...

**Comment by pirate** [comment]
Not worth the effort unless Firefox/opera/safari have an easy headless screenshot mode.

**Comment by kaptoxic** [comment]
I see. After searching a bit, it seems Firefox indeed does not have that at the moment...

**Comment by pirate** [comment]
If you have something against google, you can always use chromium instead.  It works just as well.

**Comment by kaptoxic** [comment]
I am not sure what do you mean by the first part of your sentence. Nevertheless, I do like running open source software. To that end chromium support sounds good. Thanks!
(If by any chance a possibility for supporting Firefox pops up later on, that would be pretty cool as well.)

**Comment by pirate** [comment]
For anyone finding this as of >2019, Firefox [now has a headless mode too](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Headless_mode).  There's already an open PR to add it to ArchiveBox: https://github.com/pirate/ArchiveBox/pull/217, but it probably wont land until v0.4.0 has been out for a while and the PR has been updated to support the new version.
