### ISSUE TITLE
Use of Jinja2 to render HTML content

### ISSUE THREAD

**Issue by RamolaWeb** [pirate/pocket-archive-stream#15]
The Current Script to archive the website URL  contains both python as well as the HTML code . Thus in order to scale the project i.e to modify the HTML code to redesign the Web Page to display the archive, we may need to modify the Script also. Thus it will great to use a template rendering library like Jinja2 to render the HTML content so that the HTML and Python Part Can be separated.

**Comment by pirate** [comment]
PR welcome, the script has no python dependencies currently, ideally I'd like to keep it that way.
