### ISSUE TITLE
Dependency error google-chrome, though Chromium installed

### ISSUE THREAD

**Issue by mraduldubey** [pirate/pocket-archive-stream#16]
Ubuntu, gives an error for dependency. It needs google-chrome to work. Enable it to work with Chromium at t least. They are essentially the same.

**Comment by RamolaWeb** [comment]
@mraduldubey  I have installed the google-chrome-beta through the given instruction as follow
- wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
- sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
- apt update
- apt install google-chrome-beta python3 wget
As it is provided in the README.MD and everything look fine

**Comment by pirate** [comment]
@mraduldubey provide us with an error message or something please, otherwise there's no way we can help you.

**Comment by mraduldubey** [comment]
@pirate  Thanks. Though that would be 'chromium-browser' not 'chromium'. Thanks for the script. It's awesome.
