### ISSUE TITLE
--print-to-pdf not working in Chromium

### ISSUE THREAD

**Issue by mraduldubey** [pirate/pocket-archive-stream#17]
The script works fine except the pdf are not being generated while using Chromium browser instead of Chrome. I have not tried it for Chrome yet. The --print-to-pdf is not working in the script though no exception is being generated.
![bug](https://cloud.githubusercontent.com/assets/13887642/26463104/d757b316-41a0-11e7-87a8-b454d8d4e49f.png)
So as a quick fix, I used wkhtmltopdf but the pdf output rendered by it is not up to the mark. Am I wrong or the code needs a bit tweaking?

**Comment by pirate** [comment]
Looks like like chromium-browser is pinned at v58 on ubuntu 16.04, I recommend installing it from dpkg instead to get the most recent version with PDF support:
https://www.chromium.org/getting-involved/download-chromium
