### ISSUE TITLE
Support parsing links from browser bookmark exports

### ISSUE THREAD

**Issue by pirate** [pirate/pocket-archive-stream#18]
Google Chrome supports exporting links from the bookmark manager as an HTML file.

It'll be trivial to add a parser for bookmark exports, it just involves adding a new service type and parser.

**Comment by wlhlm** [comment]
The HTML export is supported by many browsers and bookmarking services.

- [Netscape Bookmark File Format](https://msdn.microsoft.com/en-us/library/aa753582(v=vs.85).aspx)
- [Sample](https://gist.github.com/jgarber623/cdc8e2fa1cbcb6889872)
- [HTML->JSON Converter written in Python](https://github.com/jhh/netscape-bookmark-converter).

Firefox at least also supports exporting bookmarks as JSON ("backup"). I haven't found documentation about the format, but should be fairly straight forward to parse.

**Comment by wlhlm** [comment]
@ilvar Thank you!
